global:
  rbac:
    create: true
    pspEnabled: false
nodeExporter:
  enabled: false
alertmanager:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubelet:
  enabled: false
  serviceMonitor:
    cAdvisor: false
kube-state-metrics:
  metricLabelsAllowlist:
  - nodes=[agentpool,node_kubernetes_io_instance-type]
grafana:
  enabled: false
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'custom-endpoints-scrape'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_label_app_kubernetes_io_version]
            target_label: app_kubernetes_io_version
            action: replace
